language: python

dist: xenial

sudo: required

python:
  - '3.5'
  - '3.6'
  - '3.7'

install:
  - "pip install tox-travis"
  - "pip install flake8"

script: tox

after_success:
  - sleep 10  # Github build status would not be updated by "codecov" otherwise
